### ISSUE TITLE
Program Crashes after start.

### ISSUE THREAD

**Issue by Flashboyv2** [NikitaBeloglazov/ytcon#7] opened 2023-10-15 14:45 UTC
## Hardware Information:
- **Model:**                         Lenovo Legion 5 Pro 16IAH7H
- **Memory:**                                      16,0 ГиБ
- **CPU:**                                   12th Gen Intel® Core™ i7-12700H × 20
- **GPU:**                                     Intel® Graphics (ADL GT2)
- **GPU 1:**                                   NVIDIA GeForce RTX™ 3060 Laptop GPU
- **Disk Size:**                               (null)

## Software Information:
- **ОS:**                                 Fedora Linux 39 Beta (Workstation Edition)
- **OS Build:**                                   (null)
- **Тип ОС:**                                      64-бит
- **GNOME Version:**                                45.0
- **Window manager:**                           Wayland
- **Kernel version:**                                 Linux 6.5.6-300.fc39.x86_64

### Error output:
An unknown error has occurred!

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ytcon/yt.py", line 1261, in clipboard_checker
    new_clip = pyperclip.paste()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyperclip/__init__.py", line 681, in lazy_load_stub_paste
    return paste()
           ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyperclip/__init__.py", line 163, in paste_gtk
    clipboardContents = gtk.Clipboard().wait_for_text()
                        ^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/gi/__init__.py", line 69, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

**Comment by NikitaBeloglazov** [comment] 2023-10-15 15:21
Hellow!:3
Thanks you for report

This issue related to "paperclip", because it is not in maintenance anymore. In last commits we changed "paperclip" module to "clipman", but they have not yet been tested and marked as a release, that is, the fix is ready!

Today I will test and mark them as a release, so just wait a bit 💨👟

**Comment by NikitaBeloglazov** [comment] 2023-10-15 16:10
## ✅ Fixed!
Now, just update YTCON
- **If you installed if via pip - `pip install -U ytcon`**
- If you installed if via pipx - `pipx upgrade ytcon`

Make sure that the version is updated to v0.0.15, if a message appears that the newest version is v0.0.14, try again.

https://github.com/NikitaBeloglazov/ytcon/releases/tag/v0.0.15
Thanks for using YTCON! ❤️

###### If the problem is resolved, write about it and close the Issue. If no response is received within 14 days the Issue will be closed automatically

**Comment by NikitaBeloglazov** [comment] 2023-10-22 20:52
Closed due inactivity

**Closed by NikitaBeloglazov** 2023-10-22 20:52 UTC
Labels: bug, dependencies issue
